### ISSUE TITLE
Instructions for the Prototype Inference Server

### ISSUE THREAD

**Issue by gwanjong** [EMDC-OS/power-aware-triton#6]
I would like to know how to use the provided source code for the prototype inference server.  

Could you please provide detailed instructions on how to set it up and run it?  

Thank you for your support in advance!

**Comment by JunyeolYu** [comment]
Thank you for your question.

To set up and use the prototype inference server, you can follow these steps:

1. Clone the repository from the following link:  
   https://github.com/triton-inference-server/server/tree/v2.7.0

2. Replace the `src` folder in the cloned repository with the `src` folder from **our repository.**

3. Refer to the Triton documentation for instructions on building and running the server.


By following these steps, you should be able to set up and run the server successfully. If you encounter any issues, feel free to reach out.  

Thank you.
