### ISSUE TITLE
Example or Explanation of Log Contents

### ISSUE THREAD

**Issue by ChanuYu** [EMDC-OS/power-aware-triton#7]
Could you share an example of the log output or describe the types of information it contains?

For instance, does it include details such as timestamps, request processing, resource utilization, or error messages?  

Understanding the log structure and content would be very helpful for analyzing the system’s performance and behavior.  

Thank you for your help!

**Comment by JunyeolYu** [comment]
Thank you for your question.

The terminal output from the simulation includes the following information:

1. Parameter Information:  
2. Optimal Cluster Allocation (Approach 1):  
3. Heuristic Cluster Allocation (Baseline of Approach 1):  
4. Power Consumption:  
5. Energy Consumption:  

These outputs provide a comprehensive overview of the simulation's performance and resource usage. If you need further clarification or assistance, please let me know.

Thank you!
