### ISSUE TITLE
Q. Simulation Options

### ISSUE THREAD

**Issue by ChanuYu** [EMDC-OS/power-aware-triton#8]
Hello,  

The simulation code includes five different options, but their specific purposes and functionalities are not clear.  

Could you please explain what each of these options corresponds to and how they affect the simulation?  

Having a detailed understanding of these options would be very helpful for running and reproducing the experiments accurately.  

Thank you.

**Comment by JunyeolYu** [comment]
Thank you for your question.

The simulation code's options (op1-op5) correspond directly to the five items listed in **Figure 12 of the paper**. Below is a brief explanation for each:

- Option 1: Cluster-Alloc
- Option 2: Node-Scaling
- Option 3: GPU-Scaling
- Option 4: Clock-scaling
- Option 5: Baseline

If you need further clarification on the other options or additional details about how these relate to the simulation, feel free to ask.

Thank you!
